Implement Support for Executing CLF Workflows
colour-science/colour pull request #1310
Opened 2024-11-07 14:41 UTC by MichaelMauderer

# Summary

Add support for executing CLF workflows defined as per https://docs.acescentral.com/specifications/clf/#common-lut-format-clf-a-common-file-format-for-look-up-tables

Closes #636 

# TODO
* [ ] Extend documentation
* [ ] Add tests for more complex workflows
* [ ] Add better error handling for invalid inputs
* [ ] Create a release of the CLF IO package and update the `pyproject.toml`to use that instead of directly referring to the repo. 

# Preflight

**Code Style and Quality**

- [ ] Unit tests have been implemented and passed.
- [ ] Pyright static checking has been run and passed.
- [ ] Pre-commit hooks have been run and passed.
- [ ] New transformations have been added to the _Automatic Colour Conversion Graph_.
- [ ] New transformations have been exported to the relevant namespaces, e.g. `colour`, `colour.models`.

**Documentation**

- [ ] New features are documented along with examples if relevant.
- [ ] The documentation is [Sphinx](https://www.sphinx-doc.org/en/master/) and [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant.

2024-11-14 08:31 UTC, KelSolaar requested changes
Thanks Michael for the work! This is just a first batch of important notes WRT to the implementation, core idea is that we try as much as possible to use our existing code.

2024-11-14 08:31 UTC, KelSolaar commented on colour/io/luts/clf.py
> +    R, G, B = tsplit(value)
**Minor**

We should be able to do something along the line of `np.sum(weights * value, axis=-1)` to avoid the `tsplit`.

2024-11-14 08:31 UTC, KelSolaar commented on colour/io/luts/clf.py
> +def apply(
**Major**

We should try to use `colour.io.LUTSequence` here.

2025-01-08 13:21 UTC, MichaelMauderer commented on colour/io/luts/clf.py
> +def apply(
Done.

2025-01-08 13:21 UTC, MichaelMauderer commented on colour/io/luts/clf.py
> +from colour_clf_io.values import Channel
They seem to be running without error on my machine at the moment.

2025-01-08 13:22 UTC, MichaelMauderer commented on pyproject.toml
> +colour-clf-io = {git = 'https://github.com/colour-science/colour-clf-io.git'}
Definitely. Just wanted to wait until everything else is ironed out.

2025-01-08 13:27 UTC, MichaelMauderer commented on pyproject.toml
> +    "colour-clf-io"
This needs to be done after the  `clf_io` package is released.

2025-03-01 21:01 UTC, KelSolaar commented
Thanks @MichaelMauderer! Not a full review yet because I would like to tame some high level issues first before going deeper.

## Singleton Behaviour

Was there any reason to have a `node` class global attribute here:

```python
class CLFNode(AbstractLUTSequenceOperator):
    node: clf.ProcessNode

    def __init__(self, node: clf.ProcessNode) -> None:
        super().__init__(node.name, node.description)
        self.node = node
```

The consequence is that if we instantiate multiple CLF nodes of the same type, they behave like a singleton and changing one will change all the others:

![image](https://github.com/user-attachments/assets/4c20319a-c33f-44b6-9b46-cac747e35efb)

I think that this would be better:

```python
class CLFNode(AbstractLUTSequenceOperator):
    def __init__(self, node: clf.ProcessNode) -> None:
        super().__init__(node.name, node.description)
        self._node = node

    @property
    def node(self) -> clf.ProcessNode:


class LUT3D(CLFNode):
    def __init__(self, node: clf.LUT3D) -> None:
        super().__init__(node)
        # self.node = node  <--- We don't even need to assign it here because it is taken care of in the super class.
```

The classes from `colour_clf_io` are fine because they are `@dataclass` decorated:

```
import colour_clf_io as clf

LUT_1 = clf.LUT1D("Foo", "Bar", clf.BitDepth.f32, clf.BitDepth.f32, "Baz", clf.Array([0, 1, 2, 3, 4], [0, 1, 2, 3, 4]), False, False, clf.Interpolation1D.LINEAR)
LUT_2 = clf.LUT1D("John", "Doe", clf.BitDepth.f16, clf.BitDepth.f16, "Luke", clf.Array([4, 3, 2, 1, 0], [4, 3, 2, 1, 0]), True, True, clf.Interpolation1D.LINEAR)

print(LUT_1.array)
print(LUT_2.array)
```

```
Array(values=[0, 1, 2, 3, 4], dim=[0, 1, 2, 3, 4])
Array(values=[4, 3, 2, 1, 0], dim=[4, 3, 2, 1, 0])
```

BTW, I noted that `colour_clf_io .XMLParsable` already inherits from `ABC` thus we can simplify `colour_clf_io.ProcessNode` inheritance and remove `ABC`:

```
@dataclass
class ProcessNode(XMLParsable, ABC)
```

## `apply`

Instead of having an `apply` function, why don't we override `LUTSequence.__init__` so that usage becomes something along those lines which is consistent with the way we apply LUTs, etc...:

```
class CLFProcessList(LUTSequence):
     def __init__(process_list: clf.ProcessList):
          ...

my_CLF = CLFProcessList(process_list)
RGB = my_CLF.apply(RGB)
```

2025-03-07 12:15 UTC, MichaelMauderer commented
>
> ## Singleton Behaviour
> ...

Thanks for spotting this! This bit was a bit tricky due to typing requirements. We want the `CLFNode` node to have access to a `clf.ProcessNode`, but each subclass needs to have access to the actual subclass of `clf.ProcessNode` that it's based on, so it can access the specific attributes. Unfortunately, the proposed solution doesn't allow for that, as it erases the specific type of the node used. The solution I've arrived at is a bit more verbose, but seems to work fine:

```
class CLFNode(AbstractLUTSequenceOperator):
    def __init__(self, node: clf.ProcessNode) -> None:
        super().__init__(node.name, node.description)

    @property
    @abstractmethod
    def node(self) -> clf.ProcessNode:

class LUT3D(CLFNode):
   
    def __init__(self, node: clf.LUT3D) -> None:
        super().__init__(node)
        self._node = node

    @property
    def node(self) -> clf.LUT3D:
        return self._node
```
This passes type checking and avoids the singleton bug. 


>
> ## ``apply``
> ...

I agree that is a much better API. I went with the `apply` approach to keep the `colour_clf_io` API out of the public API of `colour` for stability reasons. But as discussed, we could just move this whole PR to `colour_clf_io` and avoid the issue completely. 
There we can add the `CLFProcessList` you propose here behind an optional feature that adds `colour` as a dependency to `colour_clf_io`.

2025-03-19 11:26 UTC, closed without merging

2025-03-19 11:26 UTC, MichaelMauderer commented
I'm closing this in favour of https://github.com/colour-science/colour-clf-io/pull/5