Added support for Rayleigh-Jeans spectral distribution
colour-science/colour pull request #934
Opened 2022-01-30 18:25 UTC by Alt-Shivam

(cherry picked from commit 285fef1b3cbab66064244ef92259de7bf5122783)
Related to issue #919

2022-01-30 18:28 UTC, Alt-Shivam commented
@KelSolaar sir 
I hope I am going right.
Please have a look and suggest changes, If any

2022-02-04 14:06 UTC, Alt-Shivam commented
@KelSolaar sir 
Please trigger workflows once again.

2022-02-04 15:29 UTC, Alt-Shivam commented
Resolved all the errors 
except this 
![image](https://user-images.githubusercontent.com/81817735/152555885-69e95ef9-e7b6-46d2-be96-e5df0c603ed6.png)


because there is no trailing whitespace at that location.

2022-02-05 00:38 UTC, KelSolaar commented
Hi @Alt-Shivam,

The white space is here: `where "c" is the speed of light; `

Even with that fixed, the docstring is incorrect, it should have proper parameters described.

There is also no reason to have a new module header middle of the module, i.e. this should not be here:

```python
"""
Rayleigh-Jeans spectral distribution
==============================

Defines the objects to compute the Rayleigh–Jeans law approximation to
the spectral radiance of electromagnetic radiation as a function of
wavelength from a black body at a given temperature through
classical arguments.
"""
```

Before I start to review, would it be please possible to add:

- Unit tests in *colour/colorimetry/tests/test_blackbody.py*
- Examples in *colour/examples/colorimetry/examples_blackbody.py*

Cheers,

Thomas

2022-02-12 01:49 UTC, KelSolaar requested changes
Hi @Alt-Shivam,

Thanks for the PR, I left a few minor stylistic comments. It would be interesting
to put an example in `colour/examples/colorimetry/examples_blackbody.py` maybe!

Cheers,

Thomas

2022-02-12 01:49 UTC, KelSolaar commented on colour/colorimetry/blackbody.py
> +    wavelength,
We will need the typing annotations like for the `planck_law` definition.

2022-02-12 01:49 UTC, KelSolaar commented on colour/colorimetry/blackbody.py
> +    Returns the spectral radiance of electromagnetic radiation as a
We are now using imperative docstring style, thus `Returns the ...` should be `Return the ...`

2022-02-12 01:49 UTC, KelSolaar commented on colour/colorimetry/blackbody.py
> +    :math:`T[K]` in a medium having index of refraction :math:`n`.
``index of refraction :math:`n`.`` --> ``index of refraction :math:`n` according to *Rayleigh–Jeans* law.``

2022-02-12 01:49 UTC, KelSolaar commented on colour/colorimetry/blackbody.py
> +
We will need a `References` section here. You can use ``:cite:`Wikipedia2003f`` and the following top level reference:

```reStructuredText
-   :cite:`Wikipedia2003f` : Wikipedia. (2003). Rayleigh–Jeans law. Retrieved
    February 12, 2022, from https://en.wikipedia.org/wiki/Rayleigh–Jeans_law
```

2022-02-12 01:49 UTC, KelSolaar commented on colour/colorimetry/blackbody.py
> +    temperature,
Ditto for the typing annotations! :)

2022-02-12 01:49 UTC, KelSolaar commented on colour/colorimetry/blackbody.py
> +    Returns the spectral distribution of the Spectral radiance for
Same for `Returns` vs `Return` and also `Spectral` is capitalised.

2022-02-12 01:49 UTC, KelSolaar commented on colour/colorimetry/blackbody.py
> +    (:math:`W/sr/m^2/nm`).
` according to *Rayleigh–Jeans* law.`

2022-02-12 01:49 UTC, KelSolaar commented on colour/colorimetry/blackbody.py
> +
We can copy the `References` section from the function above.

2022-02-12 01:49 UTC, KelSolaar commented on docs/colour.colorimetry.rst
> +    sd_rayleigh_jeans
the `rayleigh_jeans_law` definition should be documented in the section just after.

2022-02-12 06:53 UTC, Alt-Shivam commented
Unit tests in colour/colorimetry/tests/test_blackbody.py
Examples in colour/examples/colorimetry/examples_blackbody.py
I am still working on them.

And thanks for the constant support sir 😊

2022-02-15 18:34 UTC, Alt-Shivam commented
Hey @KelSolaar sir 
Added Unit test for Rayleigh-Jeans law 
but still struggling with the test data.
Constantly trying for the last 3days.
But still........

Can you please help me out. 
Thanks 😊

2022-02-15 23:25 UTC, KelSolaar commented
Can you please do not merge develop in your branch please? Always rebase! Is it possible to reset hard your branch to before the merge you did and force-push to pop the merge out?

2022-02-16 02:09 UTC, Alt-Shivam commented
Again same mistake 😶
Merged develop while resolving conflicts. 
Will try to figure out what can be done now .
Thanks sir

2022-06-05 07:26 UTC, KelSolaar commented
Closing in favour of #995 as this PR is unfortunately not in a state where it can be merged.

2022-06-05 07:26 UTC, closed without merging